### ISSUE TITLE
API Docs and DB Diagram Adjustments

### ISSUE THREAD

**Issue by AnthonyBronca** [RWilson-Tyr/EarthNbN#1]
# API Docs:
- [x] Add db diagram image to the api docs .md file
- [x] `Get All Spots owned by the Current User route` is not RESTFUL
- [x] `Create a spot` Route is not RESTFUL
- [x] `Add an image to spot` Route is not RESTFUL
- [x] `Edit a Spot` Route is not RESTFUL
- [x] `Delete a Spot` Route is not RESTFUL
- [x] `Get all Reviews of the Current User` Route is not RESTFUL
- [x] Fix the rest of the additional routes to follow RESTFUL route naming convention
- [x] `Add Query Filters to Get all Spots` Route is not RESTFUL.
- [x] Add a .md reference to the image on API docs, so that it appears within the same file

# DBDiagram:
- [x] avgRating is Aggregate data and should not be on our table
- [x] Readjust Preview Image as some of the functionality is limited on Spots table, and it is redundant since we have a related table via a `BOOL` attribute.

# General items:
- [x]  Remove Zone Identifiers from Repo

## Deadline
Please mark these off as you go. Please request another review if completed. API docs and DB Diagram are due by EOD on Monday, May 13th.

**Comment by irelius** [comment]
# API Doc and DB Diagram Review 2

## DB Diagram
- [ ] "fName" and "lName" under the User table does not match the expected response detailed by the API doc
- [ ] There is a "reviewImgId" under the Reviews table that is not necessary
- [ ] Table name for SpotImgs and ReviewImg do not match the API docs

## API Doc
- [ ] Method for login should be a POST. Note that if you change the method from GET to POST, it'll be the same as the signup route. Recommend changing/adding information in the route to specify what they'll be doing.
- [ ] Route for "Get all Spots owned by the Current User" is not ideal. For example, if user 1 wanted to get their spots, the api endpoint would look like: "/1/spots". However, this endpoint is not the cleanest as you don't know if the "1" is referring to a spot, user, or anything else.
- [ ] Route for getting all reviews by current user has similar issue as above. Endpoint should include detail to indicate it's the reviews that belong to a specific user
- [ ] Route for getting all bookings by current user has similar issue as above
- [ ] Route for "Add an Image to a Spot based on the Spot's id" is not ideal as it doesn't tell you that you're creating an image for a particular spot
- [ ] Route for "Add an Image to a Review based on the Review's id" has similar issue as above. Route doesn't indicate you're creating an image for a particular review
- [ ] Route for "Delete a Spot Image" won't break, but it is longer than necessary. Since you have a table dedicated to SpotImgs that are only children of spots, specifying the parent spot id is not necessary. If you want to keep it, you can, but you'd need to then revise the current route to follow restful convention. The spotImageId parameter should come after the resource (table) that it's referencing.
- [ ] Route for "Delete a Review Image" similar to above. (Again, shouldn't cause anything to break, but best to think/revise it a bit)

**Comment by RWilson-Tyr** [comment]
Finished review 2. Ready for a check.
